export const surveyData = [
  
    {
        id: -3,
        question: "Please enter your TOWN/CITY and STATE",
    
      },

    {
      id: -2,
      question: "Please Specify your GENDER"
    },

    {
      id: -1,
      question: "Please specify your AGE"
    },

    {
      id: 0,
      question: "What is your Employement Status?"
    },
  
    { id: 1, question: "Ever since my child/children left home I feel that I am satisfied in my life." },
    { id: 2, question: "Ever since my child/children left home I often tend to experience a sense of emptiness." },
    { id: 3, question: "Ever since my child/children left home I feel bitter when I see other parents with their children." },
    { id: 4, question: "I don’t like the fact that my child had to leave the house for work/studies/marriage." },
    { id: 5, question: "My routine has been the same since my child/children have left home." },
    { id: 6, question: "Ever since my child/children left home I find myself looking back on memories." },
    { id: 7, question: "Delay in/unable to contact my child/children causes a lot of stress and anxiety." },
    { id: 8, question: "Ever since my child/children left home, I have thoughts of not being able to see him/her/them for one last time when I fall ill." },
    { id: 9, question: "Ever since my child/children left home there have been lesser conflicts." },
    { id: 10, question: "I need to constantly check on my child/children to assure myself that they are okay." },
    { id: 11, question: "I do not feel like eating the food I make on special occasions knowing that I cannot share it with my child/children." },
    { id: 12, question: "Ever since my child/children left home I feel like I have more time on my hands to do the things I enjoy." },
    { id: 13, question: "I feel sad when I am not able to celebrate my child/children’s accomplishments with them in person." },
    { id: 14, question: "Ever since my child/children left home I feel more irritable than before." },
    { id: 15, question: "Ever since my child/children left home I constantly worry about my child’s/children’s safety." },
    { id: 16, question: "Ever since my child/children left home I feel aches/pains in my body that do not seem to go away no matter what I try." },
    { id: 17, question: "Ever since my child/children left home I often feel sad for no apparent reason." },
    { id: 18, question: "I feel okay about my child moving away from home." },
    { id: 19, question: "My child moving away has not affected me emotionally." },
    { id: 20, question: "Ever since my child/children left home I lack the energy to do my work daily." },
    { id: 21, question: "I have lost my appetite ever since my child/children left home." },
    { id: 22, question: "Ever since my child/children left home I find myself with more free time these days and do not know how to occupy myself." },
    { id: 23, question: "Ever since my child/children left home I find myself in a good mood most of the time." },
    { id: 24, question: "When my child is unwell, I worry and feel helpless for not being able to take care of them." },
    { id: 25, question: "I don't like that my child/children don't talk to me enough and that we're growing apart." },
    { id: 26, question: "Ever since my child/children left home I feel abandoned by my child." },
    { id: 27, question: "I worry that I might be disturbing my child/children when I call them." },
    { id: 28, question: "Ever since my child/children left home I feel anxious when I am unaware of their routine." },
    { id: 29, question: "Moving away from home is a good opportunity for my child/children to become independent and grow." },
    { id: 30, question: "There has been an increase in the amount of work I do around the house after my child has left home." },
    { id: 31, question: "I have not constantly thought about my child/children since they have left home." },
    { id: 32, question: "When my child is facing difficulties, I feel guilty for not being physically present with them." },
    { id: 33, question: "Ever since my child/children left home I can take care of my health, wellness, and appearance better." },
    { id: 34, question: "Ever since my child/children left home I feel like I have lost my friend." },
    { id: 35, question: "Ever since my child/children left home I do not find joy in activities that previously interested me." },
    { id: 36, question: "I don’t feel like attending any family occasions/gatherings/ any fun event without my child/children." },
    { id: 37, question: "I tend to use my phone a lot to distract myself ever since my child/children have left home." },
    { id: 38, question: "Ever since my child/children left home I feel that I can focus more on what I usually do and its demands." },
    { id: 39, question: "I tend to talk about my feelings of sadness with family and friends after my child/children left home." },
    { id: 40, question: "I can enjoy festivities and special occasions despite not having my child/children around." },
    { id: 41, question: "I do not feel safe and secure without my child/children in the house." },
    { id: 42, question: "I am unable to communicate as much as I’d like with my child/children because I lack technological knowledge." },
    { id: 43, question: "I feel I have lost a major part of my identity because I no longer can get involved with my child/children's life events." },
    { id: 44, question: "Ever since my child/children left home my sleep cycle is disturbed because of a constant worry." },
    { id: 45, question: "Ever since my child/children left home I enjoy spending more time with my friends now." },
    { id: 46, question: "Ever since my child/children left home I feel like I have nobody to talk to in my daily life." },
    { id: 47, question: "I feel that my child/children leaving has negatively impacted my marriage/relationship with my spouse." },
    { id: 48, question: "Ever since my child/children left home I find myself interacting more with children around me." },
    { id: 49, question: "I prepare for my child’s visit and plan a lot way before they come home." },
    { id: 50, question: "Ever since my child/children left home I feel positive about my family’s future." },
    { id: 51, question: "I like most parts of my personality." },
    { id: 52, question: "When I look at the story of my life, I am pleased with how things have turned out so far." },
    { id: 53, question: "Some people wander aimlessly through life, but I am not one of them." },
    { id: 54, question: "The demands of everyday life often get me down." },
    { id: 55, question: "In many ways I feel disappointed about my achievements in life." },
    { id: 56, question: "Maintaining close relationships has been difficult and frustrating for me." },
    { id: 57, question: "I live life one day at a time and don't really think about the future." },
    { id: 58, question: "In general, I feel I am in charge of the situation in which I live." },
    { id: 59, question: "I am good at managing the responsibilities of daily life." },
    { id: 60, question: "I sometimes feel as if I've done all there is to do in life." },
    { id: 61, question: "For me, life has been a continuous process of learning, changing, and growth." },
    { id: 62, question: "I think it is important to have new experiences that challenge how I think about myself and the world." },
    { id: 63, question: "People would describe me as a giving person, willing to share my time with others." },
    { id: 64, question: "I gave up trying to make big improvements or changes in my life a long time ago." },
    { id: 65, question: "I tend to be influenced by people with strong opinions." },
    { id: 66, question: "I have not experienced many warm and trusting relationships with others." },
    { id: 67, question: "I have confidence in my own opinions, even if they are different from the way most other people think." },
    { id: 68, question: "I judge myself by what I think is important, not by the values of what others think is important." },
    { id: 69, question: "I've been concentrating my efforts on doing something about the situation I'm in." },
    { id: 70, question: "I've been taking action to try to make the situation better." },
    { id: 71, question: "I've been trying to come up with a strategy about what to do." },
    { id: 72, question: "I've been thinking hard about what steps to take." },
    { id: 73, question: "I've been trying to see it in a different light, to make it seem more positive." },
    { id: 74, question: "I've been looking for something good in what is happening." },
    { id: 75, question: "I've been accepting the reality of the fact that it has happened." },
    { id: 76, question: "I've been learning to live with it." },
    { id: 77, question: "I've been making jokes about it." },
    { id: 78, question: "I've been making fun of the situation." },
    { id: 79, question: "I've been trying to find comfort in my religion or spiritual beliefs." },
    { id: 80, question: "I've been praying or meditating." },
    { id: 81, question: "I've been getting emotional support from others." },
    { id: 82, question: "I've been getting comfort and understanding from someone." },
    { id: 83, question: "I've been trying to get advice or help from other people about what to do." },
    { id: 84, question: "I've been getting help and advice from other people." },
    { id: 85, question: "I've been turning to work or other activities to take my mind off things." },
    { id: 86, question: "I've been doing something to think about it less, such as going to movies, watching TV, reading, daydreaming, sleeping, or shopping." },
    { id: 87, question: "I've been saying to myself 'this isn't real.'" },
    { id: 88, question: "I've been refusing to believe that it has happened." },
    { id: 89, question: "I've been saying things to let my unpleasant feelings escape." },
    { id: 90, question: "I've been expressing my negative feelings." },
    { id: 91, question: "I've been using alcohol or other drugs to make myself feel better." },
    { id: 92, question: "I've been using alcohol or other drugs to help me get through it." },
    { id: 93, question: "I've been giving up trying to deal with it." },
    { id: 94, question: "I've been giving up the attempt to cope." },
    { id: 95, question: "I've been criticizing myself." },
    { id: 96, question: "I've been blaming myself for things that happened." }
];

export const optionsData = [
    {
    optionSet1: [
        { label: "A", text: "55-60" },
        { label: "B", text: "61-64" },
        { label: "C", text: "65-68" },
        { label: "D", text: "69+" },
      ],

      optionSet4: [
        { label: "A", text: "Working" },
        { label: "B", text: "Non Working/Retired" },
      ],

      optionSet5: [
        { label: "A", text: "Male" },
        { label: "B", text: "Female" },
      ],

      optionSet2: [
        { label: "A", text: "Strongly agree" },
        { label: "B", text: "Somewhat agree" },
        { label: "C", text: "A little agree" },
        { label: "D", text: "Neither agree nor disagree" },
        { label: "E", text: "A little disagree" },
        { label: "F", text: "Somewhat disagree" },
        { label: "G", text: "Strongly disagree" },
      ],

      optionSet3: [
        { label: "A", text: "Always" },
        { label: "B", text: "Very Frequently" },
        { label: "C", text: "Often" },
        { label: "D", text: "Sometimes" },
        { label: "E", text: "Rarely" },
        { label: "F", text: "Never" },
      ],
    }
];
